os: osx
osx_image: xcode10.2
language: node_js
node_js: '12'
script:
  - npm cache --force clean
  - npm run dist
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - dist/GrinchPlayer-*-mac.zip
    - dist/GrinchPlayer*.AppImage
  skip_cleanup: true
  on:
    tags: true
